### ISSUE TITLE
Registro usuarios

### ISSUE THREAD

**Issue by solfonte** [Fifiuba/users-service#3]
Involucra tanto registro de pasajeros como de choferes

**Comment by agustinaa235** [comment]
- CA 1: Registro exitoso
Cuando el registro del usuario es correcto.
Entonces el sistema creará un nuevo usuario con su perfil y billetera correspondiente. Luego permitirá el ingreso al sistema.
- CA 2: Obtención de ubicación
Cuando el registro del usuario es correcto.
Entonces el sistema deberá solicitarle al usuario una ubicación predeterminada
- CA 3: Obtención de perfil (Para choferes)
  Cuando el registro del usuario es correcto.
  Entonces el sistema deberá solicitarle al usuario datos sobre su persona y el vehículo que utilizara.
- CA 4: Falta uno o más campos obligatorios
Cuando el registro del usuario es incorrecto debido a un ingreso erróneo o faltante de campos.
Entonces el sistema indicará los campos faltantes y/o erróneos y no permitirá el ingreso al sistema.
- CA 5: Registro fallido
Cuando el registro del usuario falla debido a un error del servicio.
Entonces el sistema indicará un mensaje de error acorde al usuario.

**Comment by alejovillores** [comment]
- [ ]  controllers pasajeros
- [ ]  controllers choferes
- [ ]  servicios pasajeros
- [ ] servicios choferes
- [ ] modelos de bdd
